### ISSUE TITLE
Update which Ubuntu distros supported in download.php

### ISSUE THREAD

**Issue by JohnVeness** [qbittorrent/qBittorrent-website#145]
The following lines https://github.com/qbittorrent/qBittorrent-website/blob/b07e4e601c4c1e4040b72206cd3a8b3c331644c5/download.php#L232-L233 say what Ubuntu distros are supported by the PPAs but I think they are out of date, as I think 20.04 is now supported, and possibly older versions are no longer supported. I'm not definite enough to make a PR myself as I haven't actually tested!

**Comment by FranciscoPombal** [comment]
@JohnVeness 

These are the currently supported Ubuntu versions:

- `18.04`
- `20.04`
- `20.10` (it will be released this month, and will be supported for 9 months)

The 19.04 and 19.10 intermediate releases are EOL already.

Feel free to submit a PR!
