### ISSUE TITLE
[求助]我设置了 https的证书后 无法打开页面了 如何恢复

### ISSUE THREAD

**Issue by cnhap** [qbittorrent/qBittorrent-website#158]
我设置了 https的证书后 无法打开页面了 如何恢复  配置在哪里
现在用 http://192.168.10:8080 可以弹出 登陆界面 输入账号密码后 会调转到 https://192.168.1.10:8080 但网页无法显示.求助 如何恢复  我是安装在 freenas 里的 
https://github.com/freenas/iocage-ix-plugins/issues/267

**Comment by Chocobo1** [comment]
Wrong repository. File a proper issue at here: https://github.com/qbittorrent/qBittorrent/issues
