### ISSUE TITLE
Where are old versions?

### ISSUE THREAD

**Issue by LostAccount** [qbittorrent/qBittorrent-website#161]
Hello

My iMac is running High Sierra. I recently discovered that the current version (4.3.3) is not compatible but it got installed through an update offered by the app.

That being said, can you consider including a link to older versions of the software at qbittorrent.org or here on GitHub and/or perhaps including a mechanism in future versions that prohibit updates being offered/applied when a newer version might yields an incompatibility issue.

Thanks and I hope this message finds you well.

Best regards
—Alex

**Comment by Chocobo1** [comment]
Look at "Old Release Archive" section at the bottom of download page: https://www.qbittorrent.org/download.php
