### ISSUE TITLE
PPA for Ubuntu 22.04

### ISSUE THREAD

**Issue by georgehazan** [qbittorrent/qBittorrent-website#183]
Hi,

Ubuntu 22.04 aka Jammy was released a while ago, but qbittorrent still has no PPA for it. Would you please add it? Thanks.

Ign:4 https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy InRelease                                                                                                                                 
Err:7 https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy Release                                                
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                       
E: The repository 'https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by summerqB** [comment]
Support has been added.

**Comment by georgehazan** [comment]
Thanks alot! It works
