### ISSUE TITLE
4.5.3 library versions mentioned in news are the same as in 4.5.2

### ISSUE THREAD

**Issue by thalieht** [qbittorrent/qBittorrent-website#214]
Also the Windows build `lt20 qt6` is called `lt20 qt5` in fosshub (installer name is correct).

**Comment by xavier2k6** [comment]
library versions will be addressed via https://github.com/qbittorrent/qBittorrent-website/pull/215

**Comment by sledgehammer999** [comment]
>4.5.3 library versions mentioned in news are the same as in 4.5.2

copy pasta that I forgot to update...
Will be fixed now.
