### ISSUE TITLE
Not recieving email for password recovery.

### ISSUE THREAD

**Issue by fusk-l** [qbittorrent/qBittorrent-website#220]
I have tried multiple times, i have checked every inbox, spam etc. There is no sight of the email. I tried registering just to check if the username "fusk" was available, in case of some sort of wipe.

**Comment by PriitUring** [comment]
There's no login place in qBit website.

So, do You have issue with your email and old GitHub account?

If yes, then you need to contact official GitHub support and your email provider yourself, not post your issue here.

**Comment by fusk-l** [comment]
No, i probably just made and error, in not realizing that the forum is not a part of the website.
I'll close this and look for another way to contact a forum admin.
