### ISSUE TITLE
News RSS/Atom feed broken

### ISSUE THREAD

**Issue by jmcken1** [qbittorrent/qBittorrent-website#231]
I just noticed the qBittorrent site has a news RSS (technically, Atom) feed here:
https://www.qbittorrent.org/news_feed.atom

Unfortunately, it looks like the feed hasn’t updated since the release of v2.6.5 all the way back in 2011. It would be great if it were active again.

**Comment by Chocobo1** [comment]
>Unfortunately, it looks like the feed hasn’t updated since the release of v2.6.5 all the way back in 2011.

Why do you say that? I mean, how do you know it isn't up to date?

**Comment by jmcken1** [comment]
Neeeeeeevermind. Apparently my RSS app was being a jerk yesterday and didn’t load all the items for some reason. 😑
