### ISSUE TITLE
Update the team page

### ISSUE THREAD

**Issue by ngosang** [qbittorrent/qBittorrent-website#3]
This page looks really outdated => https://www.qbittorrent.org/team.php
Maybe we should redirect to => https://github.com/qbittorrent/qBittorrent/graphs/contributors
or => https://github.com/orgs/qbittorrent/people

**Comment by sledgehammer999** [comment]
I kept it for historical reasons. Now that that page is in git we can rewrite it. Old info will be available in git for anyone caring enough.

I propose leaving info about me, Chris and Zsolt Peter Basak(forum admin) and then linking to both Contributors and People. (with appropriate text)

**Comment by Chocobo1** [comment]
I've done some reorganization in b90e669071bf1a25d56e225729ee693bc932e7c3.
