### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by ngosang** [qbittorrent/qBittorrent-website#4]
Screenshots are hosted in sourceforge and they are really old. We should make new screenshots (in different OSs). If we have enough bandwidth in qBittorrent hosting we should upload them in this repository. If not we can use imgur or another image hosting. @sledgehammer999 

https://sourceforge.net/projects/qbittorrent/#screenshots

**Comment by sledgehammer999** [comment]
Yeah just post a few pics here so we can agree on what to use. I'll upload some of them to sf.net project page too.
I'll ask the forum admin if it is ok for the bandwidth. I think we have a lot of room.

PS: Use clean torrents in pics.

**Comment by sledgehammer999** [comment]
Admin confirmed that we can upload screenshots. We have a lot of headroom in resources.

**Comment by ngosang** [comment]
I can do screenshots in Windows 10 and Linux/KDE 5 but I have a HiDPI Screeen.

**Comment by Balls0fSteel** [comment]
I will post a few.

**Comment by Balls0fSteel** [comment]
Well, I made a ticket about this on the main tracker (visibility), but people suggested we should wait for 3.4. Once it's out I will bump that ticket up and we can roll.

**Comment by thinsoldier** [comment]
Update the screenshots already. ANY SCREENSHOTS newer and high quality than what's on the SourceForge page would be a major improvement. Put them in a dedicated page within the website. Don't send people over to sourceforge and have to load a separate slow loading site just to see screenshots. Should also update the screenshots on the sourceforge page.

**Comment by Balls0fSteel** [comment]
Post screenshots @thinsoldier ? 😺

**Comment by Chocobo1** [comment]
Done in 723c0df824392d888b4c2590ceca89ed347a5bd3.
