### ISSUE TITLE
[Navigation]Development, Bugs, Forum and Wiki buttons do not work

### ISSUE THREAD

**Issue by klemun** [qbittorrent/qBittorrent-website#41]
The 'Development', 'Bugs', 'Forum' and 'Wiki' buttons(in the main navigation bar) do not link to existing websites.

Tested on: Chrome 59, Firefox 54 and Edge

**Comment by Chocobo1** [comment]
Thanks, will be back to normal in the next few hours.

**Comment by Chocobo1** [comment]
@sledgehammer999 

The dns records I get is weird and the resolve is slow (before, when it was working), I would change the following:
```
forum.qbittorrent.org CNAME qbforums.shiki.hu
wiki.qbittorrent.org CNAME github.com/qbittorrent/qBittorrent/wiki
git.qbittorrent.org CNAME github.com/qbittorrent/qBittorrent
bugs.qbittorrent.org CNAME github.com/qbittorrent/qBittorrent/issues
```

**Comment by sledgehammer999** [comment]
That's what I was doing before. I didn't change something. It seems that GoDaddy has problems. And it seems that it goes on for days now. I still can use those subdomains to redirect....

**Comment by Chocobo1** [comment]
@sledgehammer999 
maybe its worth to try recreating the dns rules (delete and then create).

**Comment by sledgehammer999** [comment]
GoDaddy DNS had issues for the last few days. I gave up and switched to Namecheap's FreeDNS.
Subdomain redirection should start working again.
Note: It can take many hours for the DNS changes to reach every computer on the Internet. So allow some hours if you still experience problems.
