### ISSUE TITLE
List of top devs should be updated

### ISSUE THREAD

**Issue by dzmat** [qbittorrent/qBittorrent-website#47]
I have listed top devs of last 2 years using command 
git log --pretty="%an <%ae>" --since=31/08/2015 | sort | uniq -c | sort -n -r

Here is truncated top list of dev with num of patches in first column
    714 sledgehammer999 <hammered999(at)gmail.com>
    380 Chocobo1 <Chocobo1(at)users.noreply.github.com>
    156 Eugene Shalygin <eugene.shalygin(at)gmail.com>
    128 Vladimir Golovnev (Glassez) <glassez(at)yandex.ru>
     56 buinsky <vix_booja(at)tut.by>
     52 Mike Tzou <Chocobo1(at)users.noreply.github.com>
     49 ngosang <ngosang(at)hotmail.es>
     35 thalieht <yjapysgr(at)sharklasers.com>
     31 Vladimir Golovnev <glassez(at)yandex.ru>
     22 ngosang <diegodelasheras(at)gmail.com>
     21 Tim Delaney <timothy.c.delaney(at)gmail.com>
     17 Vladimir Golovnev (qlassez) <glassez(at)yandex.ru>
     11 Bert Verhelst <verhelstbert(at)gmail.com>

So i think information at site about current active developers should be corrected.

**Comment by sledgehammer999** [comment]
I assume you mean this link: https://www.qbittorrent.org/team.php

I think "Active maintainer" and "Original author" should remain.
IMO inactive contributors should go.
Forum admin mention should stay.
Nick Tiskov (aka @ gelmir ) should go.
Instead for the contributors we should link from inside that page to https://github.com/qbittorrent/qBittorrent/graphs/contributors

That's my 2cents.

**Comment by Chocobo1** [comment]
Fixed in #52.
