### ISSUE TITLE
Turkish translater name update

### ISSUE THREAD

**Issue by BouRock** [qbittorrent/qBittorrent-website#49]
Hi,

Could you update name of the Turkish translater in localization page and also in application's Translators tab as "Burak Yavuz (BouRock)"?

Regards,
Burak

**Comment by sledgehammer999** [comment]
About page is done with commit: https://github.com/qbittorrent/qBittorrent/commit/5157fc201cfdce4c62e75b051086b30692445163
The localization page of the website is very outdated and I don't want to keep it. So https://github.com/qbittorrent/qBittorrent-website/pull/51 removes it.
