### ISSUE TITLE
Add Bitcoin Cash address for donations

### ISSUE THREAD

**Issue by einsteinsfool** [qbittorrent/qBittorrent-website#54]
Fees in Bitcoin are much higher in Bitcoin Cash. Bitcoin is definitely not a good cryptocurrency for donations:
https://bitinfocharts.com/comparison/transactionfees-btc-bch.html#3m

Could you consider adding Bitcoin Cash address on the donation page?
Monero is also a cool and popular cryptocurrency, so perhaps add Monero address too.

**Comment by sledgehammer999** [comment]
Sorry, but I only support btc and ltc. I don't want to have a multitude of wallet software on my pc.
Thanks for the offer though.

**Comment by tuxayo** [comment]
Does anyone know a (simple) tool/service/way to get donations from multiple currencies and have them converted into one? Like stripe which allows to receive various fiat and have them converted in one currency.

**Comment by tuxayo** [comment]
For example, donors could just use https://shapeshift.io/ and set the reception address as sledgehammer999's LTC or BTC one.

If this is a viable option. It could be advertised in the app and the website.
