### ISSUE TITLE
RSS feed for news

### ISSUE THREAD

**Issue by andoruB** [qbittorrent/qBittorrent-website#56]
I would like to request adding a RSS feed for the development news. It would be nice to be able to track with an RSS aggregator what new stuff has been implemented in this wonderful torrent client.

**Comment by Balls0fSteel** [comment]
There are sites to generate this, but the problem is that the News are not enclosed with tags. A simple <p> tag would do, maybe call it <p class="newsentry"> or whatever.

@Chocobo1 sorry for tagging you like this, just not sure if anyone is working on the site. 
Should I just try to write an rss.php or something like that and tags for news? (As pull request?)

**Comment by Chocobo1** [comment]
>Should I just try to write an rss.php or something like that and tags for news? (As pull request?)

Yeah, I've no idea what it would be like, hope it is not too intrusive.

And I'm not sure what OP is asking, RSS for development? there is already:
https://github.com/qbittorrent/qBittorrent/commits/master.atom

RSS for release news? Then something needs to be done...
Or we can just copy release notes from our website to [Github releases](https://github.com/qbittorrent/qBittorrent/releases) and get RSS at https://github.com/qbittorrent/qBittorrent/releases.atom

**Comment by andoruB** [comment]
> RSS for release news? Then something needs to be done...

This.
I incorrectly worded my initial post.

In the meantime, I'll use the provided atom link, thanks!

**Comment by Chocobo1** [comment]
@sledgehammer999 
What do you think about my suggestion, this would be the simplest way:
>Or we can just copy release notes from our website to Github releases and get RSS at https://github.com/qbittorrent/qBittorrent/releases.atom

Or... the news are in markdown format, so theoretically it shouldn't be hard to transform to RSS feed.

>thank you Chocobo and sorry for tagging you / wasting your time.

Not a problem.

**Comment by Balls0fSteel** [comment]
I will just use the Github feeds you linked for the Discord bot. (Just to have a real time news feed in a few channels there.) Yeah I know devs are not really Discord folks, but regular users also love to follow development.)

**Comment by sledgehammer999** [comment]
I would prefer, to transform our current news page to a RSS feed.
I don't know if that is feasible though.
There's no point in converting already posted news. At least not the really old ones. This gives the ability to change(again) the format the news are posted by me in the backend. Now it is in the markdown syntax and follows a specific formatting of the news.
Maybe some simple script on our backend that:
1. Reads/parses `news.md`
2. For every markdown title in `news.md` it makes an RSS article. Maybe parse the title to give a date to the article. (It might need to change the format I right the date)
3. The body of each announcement should be part of the article body.
4. Somehow make the titles linkable (put an anchor?) so the RSS can link to them.
5. Does all the above, creates the feed and serves it to the user.

As I said, I don't know if that is feasilbe. Or if it needs a lot of work to implement.
But I am open to change the way/format I input the news into the site.

**Comment by sjehuda** [comment]
There is an [11ty plugin for RSS](https://github.com/11ty/eleventy-plugin-rss), though Atom is preferable.

---

Please inform me when you do, so I add qbittorrent.org either to the featured feeds of [Slixfeed](https://gitgud.io/sjehuda/slixfeed/-/blob/master/slixfeed/assets/feeds.toml?ref_type=heads) or to the feeds [database](https://gitgud.io/sjehuda/slixfeed/-/blob/master/slixfeed/assets/feeds.csv?ref_type=heads) or both.

**Comment by sjehuda** [comment]
I would recommend to reopen the forum topic News and add it as autodiscovery feed as suggested at #226. A link with a syndication feed icon would be also good in addition to the proposition.

**Comment by Chocobo1** [comment]
Since 0ecbb33019be02f23d561968f03873726f4be20a we now have Atom feed for News page.
You can see it rendered on the top right of the news page: https://qbittorrent.github.io/qBittorrent-website/news (this is the backup site, our main site for unknown reasons didn't pick up css changes so it won't render correctly).
The Atom feed URL is published at: https://www.qbittorrent.org/news_feed.atom

Hopefully I have implemented correctly.

cc @sledgehammer999
