### ISSUE TITLE
Outdated operating system support information

### ISSUE THREAD

**Issue by FranciscoPombal** [qbittorrent/qBittorrent-website#58]
The website (downloads section -> other binary packages -> Linux -> Ubuntu) states certain Ubuntu versions as supported by the stable/unstable PPAs, but this is not the case.
Right now:
* the stable PPA supports 14.04LTS (only the `libtorrent-rasterbar` package), 16.04 LTS, 17.04, 17.10, and 18.04 LTS; on the website it claims supporting 12.04 LTS, 14.04 LTS, 14.10, and 15.04.
* the unstable PPA supports 16.04 LTS, 17.04, 17.10, 18.04 LTS; on the website it claims supporting 14.04 LTS, 14.10, and 15.04.

This issue is possibly also present for other distro/os selections but I haven't checked for those.

EDIT: image below, illustrating the issue
![qbittorrent](https://user-images.githubusercontent.com/17580742/35304402-50ef0dfe-008d-11e8-84ea-8acfcb349331.png)

**Comment by Chocobo1** [comment]
That part is written in HTML, you could have submitted a PR instead ;)

**Comment by FranciscoPombal** [comment]
@Chocobo1 Ok, will do later today.
