### ISSUE TITLE
Broken or Blocked link

### ISSUE THREAD

**Issue by hdcTenBasePid** [qbittorrent/qBittorrent-website#62]
Windows 10 Edge and Internet Explorer x64.

On this page [https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent#Torrent_Queuing](https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent#Torrent_Queuing) the link at Slow Torrents click [here](https://www.rasterbar.com/products/libtorrent/manual.html) hasn't worked as far as I can tell, for a fair few weeks.

Good Luck

**Comment by Chocobo1** [comment]
Fixed, also the wiki is free to edit for everyone.
