### ISSUE TITLE
BTC addresses for bitcoin donation

### ISSUE THREAD

**Issue by imthenachoman** [qbittorrent/qBittorrent-website#73]
I am a bitcoin novice. I have a https://www.coinbase.com account with some coins in my BTC wallet. In order to send I need to know the BTC address. Based on https://www.qbittorrent.org/donate I think the address is 1PuTGwQvCF5hjp1uMKy7PPJqbM8uTjRtvU. Can someone please confirm? I don't want to send to the wrong place...

**Comment by sledgehammer999** [comment]
That's correct.
