### ISSUE TITLE
Forum Registration Verification errors

### ISSUE THREAD

**Issue by ctav01** [qbittorrent/qBittorrent-website#77]
The third question is only a colon, no actual question to answer.

![capture](https://user-images.githubusercontent.com/36281827/52394929-08d6cd00-2a61-11e9-8502-0f888270d108.PNG)

**Comment by Balls0fSteel** [comment]
The verification broke with an update by SMF, and hence been replaced by reCaptcha only. In the future I will work on including more and more safety measures. Hopefully SMF 2.1 will finally (yes!) release, we will update and then we can deploy safety plugins again and reduce the number of spammers.

I would like to thank everyone who ever reported spam on our forums!
