### ISSUE TITLE
Filter seeds by Tracker for web-ui

### ISSUE THREAD

**Issue by marxvr** [qbittorrent/qBittorrent-website#79]
This is very convenient for managing seeds.

Like the Software GUI
![image](https://user-images.githubusercontent.com/17882380/58532301-b25feb00-8217-11e9-8cc8-31e56351ee6e.png)

**Comment by Chocobo1** [comment]
Wrong place for such issue. File it here: https://github.com/qbittorrent/qBittorrent/issues
And please search before filing one to avoid making duplicates.
