### ISSUE TITLE
js puzzles wont let me in

### ISSUE THREAD

**Issue by twelveseas** [qbittorrent/qBittorrent-website#89]
dude remove that cancer ddos protection that makes people click hydrants and crosswalks for literally ever if you dont have all the google zonds up Uranus or using tor/vpn/proxy. we all of course want to help the development of google autopilot, but pls lets focus on bittorrent with this one. cheers

**Comment by Chocobo1** [comment]
https://www.qbittorrent.org/ doesn't have any js code.
