### ISSUE TITLE
4.2.1 installer signature mirror wrong link

### ISSUE THREAD

**Issue by samphunter** [qbittorrent/qBittorrent-website#91]
At https://qbittorrent.org/download.php the link to signature of x64 installer signature is `https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-`**4.2.0**`/qbittorrent_4.2.1_x64_setup.exe.asc/download`
correct link of course is:
`https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-`**4.2.1**`/qbittorrent_4.2.1_x64_setup.exe.asc/download`

The 32 bit version has the same issue.

**Comment by Chocobo1** [comment]
Thanks! Fixed now.
