### ISSUE TITLE
FOSSHUB Description still references Python 2.x

### ISSUE THREAD

**Issue by a-raccoon** [qbittorrent/qBittorrent-website#92]
FOSSHUB Description still references Python 2.x even though it has since been deprecated.

[https://www.fosshub.com/qBittorrent.html](https://www.fosshub.com/qBittorrent.html)

![image](https://user-images.githubusercontent.com/1052090/77906600-746f9100-7245-11ea-99fd-a42a35066a0a.png)

**Comment by sledgehammer999** [comment]
That's part of the review. Not part of the description.
